Add test to demonstrate issue #45
This is failing with gcc5 + castxml + std=c++11 flag with the
following error:

parsing files - started
DEBUG Reading project files: file by file
INFO Parsing source file "test.h" ...
DEBUG Reading source file: [test.h].
DEBUG File has not been found in cache, parsing...
DEBUG castxml cmd: /usr/bin/castxml  -std=c++11   -I. -c -x c++ --castxml-cc-gnu  "(" /usr/bin/clang -std=c++11 ")" --castxml-gccxml -o /tmp/tmpmsq0r7kr.xml test.h
DEBUG CASTXML version - None ( 1.136 )
<snip>
  File "/usr/local/lib/python3.4/dist-packages/pygccxml-1.7.2-py3.4.egg/pygccxml/parser/project_reader.py", line 544, in _relink_declarated_types
Exception: Unable to find out actual class definition: ''.
Class definition has been changed from one compilation to an other.
Why did it happen to me? Here is a short list of reasons:
    1. There are different preprocessor definitions applied on same file during compilation
    2. Bug in pygccxml.