tests: fix compilation with c++14/17
Fixes:
---------------------------- Captured stderr setup -----------------------------
/<<PKGBUILDDIR>>/.pybuild/cpython3_3.12_pygccxml/build/tests/data/core_types.hpp:57:38: error: ISO C++17 does not allow dynamic exception specifications [-Wdynamic-exception-spec]
   57 |         int some_function( double hi) const throw( exception ){
      |                                             ^~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/.pybuild/cpython3_3.12_pygccxml/build/tests/data/core_types.hpp:57:38: note: use 'noexcept(false)' instead
   57 |         int some_function( double hi) const throw( exception ){
      |                                             ^~~~~~~~~~~~~~~~~~
      |                                             noexcept(false)
1 error generated.

-----

No need to keep the throws / or to replace it with noexcept.
We are not really testing this functionality here, so lets write code that is generic enough for all c++ versions