Increase recursion limit for python, needed to fix travis build error
Three tests are failing in declarations_comparison_tester with:
RecursionError: maximum recursion depth exceeded

This is an attempt to fix it, it is not sure it will help.